#include "lv_setup.h"
#include "pin_config.h"
#include "time_func.h"
#include "ui.h"
#include <Arduino.h>

void setup() {
  lv_begin();  // Initialize lvgl with display and touch
  ui_init();   // Initialize UI generated by Square Line
  time_init(); // Initialize time and date from compiler
}

void loop() {
  lv_handler();  // Update UI
  update_time(); // Update time and date on UI
}

void logoPressed(lv_event_t *e) { Serial.println("Logo pressed"); }