// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: example_project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, 0 );
lv_obj_set_y( ui_time, -53 );
lv_obj_set_align( ui_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_time,"12:25");
lv_obj_set_style_text_color(ui_time, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_time, &ui_font_clock_60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_date, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_date, 0 );
lv_obj_set_y( ui_date, -20 );
lv_obj_set_align( ui_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_date,"Mon 26 Dec");
lv_obj_set_style_text_color(ui_date, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logo_button = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_logo_button, 104);
lv_obj_set_height( ui_logo_button, 89);
lv_obj_set_x( ui_logo_button, 0 );
lv_obj_set_y( ui_logo_button, 37 );
lv_obj_set_align( ui_logo_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logo_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_logo_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_logo_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_logo_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_logo_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_logo_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logo = lv_img_create(ui_logo_button);
lv_img_set_src(ui_logo, &ui_img_sls_logo_png);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_logo,180);

lv_obj_add_event_cb(ui_logo_button, ui_event_logo_button, LV_EVENT_ALL, NULL);

}
